### PR TITLE
Add .appendCString utility function, need review

### PR DESCRIPTION
**Pull request by p0nce**
What do you think?

### CODE REVIEW

**Comment by LunaTheFoxgirl** [comment]
I think we should use strlen to slice the pointer instead of fromStringz. That allows better compatibility with minimal runtime

**Comment by p0nce** [comment]
I can copy the implementation of fromStringz (which does exactly that) `into numem` to avoid the import.

**Comment by LunaTheFoxgirl** [comment]
> I can copy the implementation of fromStringz (which does exactly that) into `numem` to avoid the import.
> 
> OR
> 
> Only add that convenience function for `char`.

Copying the implementation seems like a good idea, we would probably want to keep stuff like that in a numem.internal module

**Comment by p0nce** [comment]
Question is: is there room for `wcslen` in the minimal runtime?

**Comment by p0nce** [comment]
Good now?

**Comment by LunaTheFoxgirl** [comment]
LGTM

**Pull request merged**
